services:
  - type: web
    name: confessions-app
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
    - key: SQLALCHEMY_DATABASE_URI
      fromDatabase:
        name: confessions-db
        property: connectionString


databases:
  - name: confessions-db
    plan: free
