services:
  - type: web
    name: confessions-app
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
      - key: SQLALCHEMY_DATABASE_URI
      - key: GOOGLE_CLIENT_ID
      - key: GOOGLE_CLIENT_SECRET

databases:
  - name: confessions-db
    plan: free
